# Generated by Django 3.2.5 on 2022-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('weather', models.CharField(blank=True, max_length=30, null=True)),
                ('h_temp', models.CharField(blank=True, max_length=30, null=True)),
                ('l_temp', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'climate',
            },
        ),
    ]
