# Generated by Django 3.2.5 on 2022-02-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220224_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='nickname',
        ),
    ]
