# Generated by Django 3.2.5 on 2022-02-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('feed_id', models.IntegerField()),
                ('is_bookmarked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.TextField()),
                ('profile_image', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('like_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('is_like', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
            ],
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['feed_id'], name='content_rep_feed_id_49ae3d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedlike',
            index=models.Index(fields=['feed_id'], name='content_fee_feed_id_1c82cf_idx'),
        ),
        migrations.AddIndex(
            model_name='feedlike',
            index=models.Index(fields=['email'], name='content_fee_email_3901d6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['email'], name='content_boo_email_03c3c8_idx'),
        ),
    ]
