# Generated by Django 3.2.5 on 2022-02-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='user_id',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='user_id',
            new_name='nickname',
        ),
    ]
